# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-dashboard

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$

Summary:    Forecasts, monitors, and other gadgets at a glance
Version:    0.1.0
Release:    1
Group:      Applications/Internet
License:    GPL-3.0-or-later
URL:        https://github.com/ichthyosaurus/harbour-dashboard
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-dashboard.yaml
Requires:   pyotherside-qml-plugin-python3-qt5 >= 1.5.0
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   python3-sqlite
Requires:   python3-requests
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.3
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Dashboard for SailfishOS is an app to give you the data you need at a glance.

Add tiles for your favorite weather forecast, pollen forecast, world clocks,
stock exchange watchers, and system monitors.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5  \
    VERSION=%{version} \
    RELEASE=%{release}

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
